name: pulsar-ml
channels:
  - conda-forge
  - defaults
dependencies:
  - python=3.10
  - numpy=1.24
  - pandas=2.0
  - scikit-learn=1.3
  - matplotlib=3.7
  - seaborn=0.12
  - jupyter=1.0
  - imbalanced-learn=0.10
  - shap=0.42
  - xgboost=1.7
  - lightgbm=4.1
  - catboost=1.2
  - joblib=1.3
  - tqdm=4.65
  - ipywidgets=8.1
  - jupyterlab=4.0
  - nbconvert=7.7
  - pip
  - pip:
    - papermill==2.4
    - watermark==2.4